/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Frank 2.0 Ultimate
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonAlunoTabela = new javax.swing.JButton();
        jButtonLivroCadastro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonFuncionárioCadastro = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButtonEmpréstimoCadastrar = new javax.swing.JButton();
        jButtonAlunoUpdate = new javax.swing.JButton();
        jButtonDeletarAluno = new javax.swing.JButton();
        jButtonLivroUpdate = new javax.swing.JButton();
        jButtonLivroDelete = new javax.swing.JButton();
        jButtonFuncionárioUpdate = new javax.swing.JButton();
        jButtonFuncionárioDelete = new javax.swing.JButton();
        jButtonEmprestimoUpdate = new javax.swing.JButton();
        jButtonEmprestimoDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ALUNO");

        jLabel2.setText("LIVRO");

        jButtonAlunoTabela.setText("Cadastrar");
        jButtonAlunoTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlunoTabelaActionPerformed(evt);
            }
        });

        jButtonLivroCadastro.setText("Cadastrar");
        jButtonLivroCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLivroCadastroActionPerformed(evt);
            }
        });

        jLabel3.setText("FUNCIONÁRIO");

        jButtonFuncionárioCadastro.setText("Cadastrar");
        jButtonFuncionárioCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionárioCadastroActionPerformed(evt);
            }
        });

        jLabel4.setText("EMPRÉSTIMO");

        jButtonEmpréstimoCadastrar.setText("Cadastrar");
        jButtonEmpréstimoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpréstimoCadastrarActionPerformed(evt);
            }
        });

        jButtonAlunoUpdate.setText("Update");
        jButtonAlunoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlunoUpdateActionPerformed(evt);
            }
        });

        jButtonDeletarAluno.setText("Deletar");
        jButtonDeletarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarAlunoActionPerformed(evt);
            }
        });

        jButtonLivroUpdate.setText("Update");
        jButtonLivroUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLivroUpdateActionPerformed(evt);
            }
        });

        jButtonLivroDelete.setText("Deletar");
        jButtonLivroDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLivroDeleteActionPerformed(evt);
            }
        });

        jButtonFuncionárioUpdate.setText("Update");
        jButtonFuncionárioUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionárioUpdateActionPerformed(evt);
            }
        });

        jButtonFuncionárioDelete.setText("Deletar");
        jButtonFuncionárioDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionárioDeleteActionPerformed(evt);
            }
        });

        jButtonEmprestimoUpdate.setText("Update");
        jButtonEmprestimoUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmprestimoUpdateActionPerformed(evt);
            }
        });

        jButtonEmprestimoDeletar.setText("Deletar");
        jButtonEmprestimoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmprestimoDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonFuncionárioCadastro)
                                    .addGap(26, 26, 26)
                                    .addComponent(jButtonFuncionárioUpdate))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButtonLivroCadastro)
                                    .addGap(26, 26, 26)
                                    .addComponent(jButtonLivroUpdate)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAlunoTabela)
                                .addGap(27, 27, 27)
                                .addComponent(jButtonAlunoUpdate)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonFuncionárioDelete)
                            .addComponent(jButtonLivroDelete)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButtonDeletarAluno))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(49, 49, 49)
                        .addComponent(jButtonEmpréstimoCadastrar)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonEmprestimoUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEmprestimoDeletar)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonAlunoUpdate)
                                    .addComponent(jButtonAlunoTabela))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonLivroCadastro)
                                .addComponent(jButtonLivroUpdate))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonFuncionárioCadastro)
                                .addComponent(jButtonFuncionárioUpdate))
                            .addComponent(jLabel3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonDeletarAluno)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonLivroDelete)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonFuncionárioDelete)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonEmprestimoDeletar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonEmpréstimoCadastrar)
                        .addComponent(jLabel4)
                        .addComponent(jButtonEmprestimoUpdate)))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlunoTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlunoTabelaActionPerformed

        AlunoCadastro aluno = new AlunoCadastro();
        aluno.setVisible(true);

    }//GEN-LAST:event_jButtonAlunoTabelaActionPerformed

    private void jButtonLivroCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLivroCadastroActionPerformed

        LivroCadastro livro = new LivroCadastro();
        livro.setVisible(true);

    }//GEN-LAST:event_jButtonLivroCadastroActionPerformed

    private void jButtonEmpréstimoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpréstimoCadastrarActionPerformed

        EmprestimoCadastro emprestimo = new EmprestimoCadastro();
        emprestimo.setVisible(true);

    }//GEN-LAST:event_jButtonEmpréstimoCadastrarActionPerformed

    private void jButtonFuncionárioCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionárioCadastroActionPerformed

        FuncionarioCadastro funcionario = new FuncionarioCadastro();
        funcionario.setVisible(true);

    }//GEN-LAST:event_jButtonFuncionárioCadastroActionPerformed

    private void jButtonFuncionárioDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionárioDeleteActionPerformed

        FuncionarioDelete funcionario = new FuncionarioDelete();
        funcionario.setVisible(true);

    }//GEN-LAST:event_jButtonFuncionárioDeleteActionPerformed

    private void jButtonAlunoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlunoUpdateActionPerformed
        AlunoUpdate aluno = new AlunoUpdate();
        aluno.setVisible(true);
    }//GEN-LAST:event_jButtonAlunoUpdateActionPerformed

    private void jButtonDeletarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarAlunoActionPerformed

        AlunoDelete aluno = new AlunoDelete();
        aluno.setVisible(true);

    }//GEN-LAST:event_jButtonDeletarAlunoActionPerformed

    private void jButtonLivroUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLivroUpdateActionPerformed

        LivroUpdate livro = new LivroUpdate();
        livro.setVisible(true);

    }//GEN-LAST:event_jButtonLivroUpdateActionPerformed

    private void jButtonLivroDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLivroDeleteActionPerformed

        LivroDelete livro = new LivroDelete();
        livro.setVisible(true);

    }//GEN-LAST:event_jButtonLivroDeleteActionPerformed

    private void jButtonFuncionárioUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionárioUpdateActionPerformed

        FuncionarioUpdate funcionario = new FuncionarioUpdate();
        funcionario.setVisible(true);

    }//GEN-LAST:event_jButtonFuncionárioUpdateActionPerformed

    private void jButtonEmprestimoUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmprestimoUpdateActionPerformed

        EmprestimoUpdate emprestimo = new EmprestimoUpdate();
        emprestimo.setVisible(true);

    }//GEN-LAST:event_jButtonEmprestimoUpdateActionPerformed

    private void jButtonEmprestimoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmprestimoDeletarActionPerformed

        EmprestimoUpdate emprestimo = new EmprestimoUpdate();
        emprestimo.setVisible(true);

    }//GEN-LAST:event_jButtonEmprestimoDeletarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlunoTabela;
    private javax.swing.JButton jButtonAlunoUpdate;
    private javax.swing.JButton jButtonDeletarAluno;
    private javax.swing.JButton jButtonEmprestimoDeletar;
    private javax.swing.JButton jButtonEmprestimoUpdate;
    private javax.swing.JButton jButtonEmpréstimoCadastrar;
    private javax.swing.JButton jButtonFuncionárioCadastro;
    private javax.swing.JButton jButtonFuncionárioDelete;
    private javax.swing.JButton jButtonFuncionárioUpdate;
    private javax.swing.JButton jButtonLivroCadastro;
    private javax.swing.JButton jButtonLivroDelete;
    private javax.swing.JButton jButtonLivroUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
